[project]
name = "miguel-dias-portfolio"
version = "0.1.0"
description = "Miguel Dias Portfolio Website"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs-material[imaging]>=9.6.9",
]
