authors:
  miguelmirandadias:
    name: Miguel Miranda Dias
    description: Data Scientist & AI Engineer | Founder
    avatar: assets/@miguelmirandadias.jpg
    url: https://www.linkedin.com/in/justmiguel/